# Generated by Django 4.0 on 2022-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
